Set-StrictMode -Version Latest

# PC Keeper — thin module loader. Each pillar lives in its own dot-sourced
# file; this file wires them together and controls the public surface.
. (Join-Path $PSScriptRoot 'Common.ps1')
. (Join-Path $PSScriptRoot 'Ui.ps1')
. (Join-Path $PSScriptRoot 'Update.ps1')
. (Join-Path $PSScriptRoot 'Audit.ps1')
. (Join-Path $PSScriptRoot 'Cleanup.ps1')
. (Join-Path $PSScriptRoot 'Security.ps1')
. (Join-Path $PSScriptRoot 'Health.ps1')
. (Join-Path $PSScriptRoot 'Disk.ps1')

Export-ModuleMember -Function @(
    'Get-OffloadTargets',
    'Resolve-OffloadAction',
    'Get-StaleOffloadPath',
    'Test-OffloadCopyMatches',
    'Invoke-Offload',
    'Get-DiskMeasureRoots',
    'New-DiskSnapshot',
    'Compare-DiskSnapshots',
    'Select-DiskBaseline',
    'Get-DiskDataDirectory',
    'Save-DiskSnapshot',
    'Read-DiskSnapshots',
    'Format-DiskNotification',
    'ConvertTo-DiskReportText',
    'Measure-DiskFolders',
    'Invoke-DiskMaintenance',
    'New-DiskScheduleAction',
    'Register-DiskSchedule',
    'Get-DiskActionCatalog',
    'ConvertTo-DiskActionCandidate',
    'Get-DiskActionTargets',
    'Invoke-DiskAction',
    'Split-CleanupCandidatesByPrivilege',
    'New-HealthTarget',
    'ConvertFrom-UninstallExePath',
    'ConvertFrom-ShimListing',
    'ConvertFrom-ShimgenNoop',
    'Get-HealthAgentCatalog',
    'Get-PeSubsystem',
    'New-HealthResult',
    'Resolve-HealthProbeResult',
    'Resolve-GuiHealthResult',
    'Find-DuplicateCommands',
    'Get-CodexStateFindings',
    'Get-HealthVerdict',
    'Save-HealthResults',
    'Read-HealthHistory',
    'Test-IsHealthProblem',
    'Format-HealthNotification',
    'ConvertTo-HealthReportText',
    'Get-HealthDataDirectory',
    'Get-HealthTargets',
    'Invoke-HealthProbe',
    'Invoke-HealthCheck',
    'Show-HealthToast',
    'New-HealthScheduleAction',
    'Register-HealthSchedule',
    'Show-HealthReport',
    'ConvertFrom-ElectronAppUpdateYaml',
    'ConvertFrom-GitHubElectronReleaseJson',
    'ConvertFrom-GitLsRemoteText',
    'ConvertFrom-WingetUpgradeTable',
    'ConvertFrom-NpmOutdatedJson',
    'ConvertFrom-NpmListJson',
    'ConvertFrom-ChocoOutdatedText',
    'ConvertFrom-ScoopStatusTable',
    'ConvertFrom-UninstallRegistryEntry',
    'ConvertTo-ElectronGitHubInventoryItem',
    'ConvertTo-LocalGitAppInventoryItem',
    'Get-InstalledLocalGitApps',
    'Get-LocalGitAppUpdateCandidates',
    'Get-MainMenuItems',
    'Get-NextMenuIndex',
    'Get-StatusGlyph',
    'Format-StatusLine',
    'Write-StatusLine',
    'Write-Header',
    'Show-Banner',
    'Get-SpinnerFrame',
    'Get-HealthGrade',
    'Show-Spinner',
    'Get-SystemHealthSummary',
    'Invoke-MainMenu',
    'Invoke-PcKeeper',
    'ConvertTo-HumanSize',
    'Format-Uptime',
    'Get-DiskUsageStatus',
    'Format-DiskLine',
    'Get-AuditReport',
    'ConvertTo-AuditReportText',
    'Export-AuditReport',
    'Show-AuditReport',
    'New-CleanupCandidate',
    'Test-IsSafeCleanupPath',
    'Select-StaleDirectories',
    'Select-OldVersionDirectories',
    'Get-DailyCleanupPlan',
    'Get-DailyCleanupTargets',
    'Get-SelectedCleanupSize',
    'Get-CleanupTargets',
    'Format-CleanupCandidate',
    'Invoke-CleanupCandidate',
    'Invoke-CleanupFlow',
    'Show-CleanupSummary',
    'New-SecurityFinding',
    'Get-ToggleFindingStatus',
    'Get-SecurityScore',
    'Get-SecurityFindings',
    'Get-FixableSecurityFindings',
    'Format-SecurityFinding',
    'Invoke-SecurityFix',
    'Invoke-SecurityFlow',
    'Show-SecurityReport',
    'Get-ProgramInventory',
    'Get-GitHubElectronUpdateCandidates',
    'Get-InstalledElectronGitHubApps',
    'Get-ProgramUpdateCandidates',
    'Get-PrivilegeBlockedUpdateCandidates',
    'Get-UpdateProviderDiagnostics',
    'Get-UpdatePrivilegeError',
    'Install-ProgramUpdateAllCommand',
    'Invoke-NativeText',
    'Invoke-ProgramUpdateAll',
    'Invoke-UpdateCandidate',
    'New-CommandShimText',
    'Test-ExternalTool',
    'Update-ChecklistState'
)
